### ISSUE TITLE
Search - Time Filter no longer works (both in main search and Related Resources search)

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_v3#25]
After the new Advanced Search commits, time filter no longer works. For example, the following search should return 50 results, but the filter doesn't seem to be getting applied at all:

![screen shot 2017-10-05 at 16 46 32](https://user-images.githubusercontent.com/19243127/31236741-e4205bac-a9ec-11e7-8852-e2cb519dc7f4.png)

The problem also applies to the Related Resources search.

**Comment by markdoub** [comment]
Should be fixed now by commit: e2c3aca

**Comment by azerbini** [comment]
Still not working on Related Resources (Attribute Filter also not working there)

**Comment by markdoub** [comment]
I just pushed a fix for this. It should work on related resources now

**Comment by azerbini** [comment]
@markdoub yes, this works now. However, as I said in my comments to the PR, I think it would be sensible for the Related Resources search to work exactly like the main search, inclusive of advanced search capabilities. I suspect this won't be too hard, since the only additional commits should regard the UI (related-resources.htm and related-resources.js)? 

Opening an enhancement ticket for this. Let me know what you think
